### ISSUE TITLE
Images by Tag

### ISSUE THREAD

**Issue by AppFolioRopes** [AppFolioOnboarding/image-sharer-mqchau#9]
#### As a user I want to view all images associated with a tag.

Acceptance criteria:
- [ ] When I click on a tag, I see a filtered list of only the images that have
  the tag I clicked on.
- [ ] The tag name (not its ID) is used to perform the filtering.

Discussion topics:
- [ ] Where should we implement this functionality?
- [ ] What happens if a user tries to manually filter by a nonexistent tag?

Dependencies:
- Image Tags

**Comment by mqchau** [comment]
Spring, before I start working on this issue. I want discuss general development plan with you.

I plan to implement this feature in Image Index page. In there, I will have a section that contains many buttons. Each button represents a tag available in the database. User will click on one of them then the list of images will change to show only images that contain those tags.

For starter, I will only allow the tag selection to be mutually exclusive. It means that user can't select more than 1 tag at a time.

Doing this way, user can't filter by a nonexistent tag.

In terms of implementation, I plan to be more front-end oriented. I know some AngularJS and can let the button click change the class/CSS style of the images to display/hide them. Do you think this approach is appropriate?

**Comment by mqchau** [comment]
Actually after looking ahead to Issue 16, a dependent on this issue, I won't use AngularJS because it would be hard to implement this:
- Each tag name is a link to the image list filtered by that tag.

So the revised plan is that to show all tag as <a> element, which has a link to a page like
/images/tag/<tag name>
I will use a new method in images controller to handle that kind of path.
